/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#71fcb6",
        background: "#f9f9f9",
        tertiary: "#795900",
        "surface-container-low": "#f4f3f3",
        "inverse-on-surface": "#f1f1f1",
        "surface-tint": "#006c45",
        "primary-container": "#3ecf8e",
        "tertiary-fixed-dim": "#f9bd22",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-surface-variant": "#3d4a41",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed": "#002112",
        "on-secondary-container": "#720b17",
        outline: "#6c7a70",
        surface: "#f9f9f9",
        secondary: "#a83639",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#5d4400",
        "on-background": "#1a1c1c",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#881d24",
        "inverse-primary": "#51df9c",
        "secondary-fixed-dim": "#ffb3b0",
        "surface-container": "#eeeeee",
        "on-tertiary": "#ffffff",
        primary: "#006c45",
        "on-tertiary-fixed": "#261a00",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffdf9f",
        "tertiary-container": "#e8ae07",
        "outline-variant": "#bbcabe",
        "on-surface": "#1a1c1c",
        "on-primary-container": "#005434",
        "surface-dim": "#dadada",
        "primary-fixed-dim": "#51df9c",
        "on-secondary-fixed": "#410006",
        "on-primary-fixed-variant": "#005233",
        "surface-container-highest": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "secondary-fixed": "#ffdad8",
        "secondary-container": "#fe7676",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-page": "24px",
        "stack-sm": "8px",
        "gutter-grid": "20px",
        "padding-card": "24px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist"],
        "label-caps": ["Geist"],
        "body-md": ["Geist"],
        "headline-md": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "body-sm": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-sm": ["Geist"],
      },
      fontSize: {
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
